# Generated by Django 4.0.7 on 2022-10-05 21:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stacks", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicalstack",
            old_name="summary",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="stack",
            old_name="summary",
            new_name="description",
        ),
    ]
