# Generated by Django 4.0.8 on 2022-11-09 01:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stacks", "0002_rename_summary_historicalstack_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalstack",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stack",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
