# Generated by Django 4.0.8 on 2022-11-09 01:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stacks", "0003_historicalstack_notes_stack_notes"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicalstack",
            old_name="description",
            new_name="subtitle",
        ),
        migrations.RenameField(
            model_name="stack",
            old_name="description",
            new_name="subtitle",
        ),
    ]
