# Generated by Django 4.0.8 on 2022-11-09 01:24

from django.db import migrations


def split_description_to_subtitle_and_notes(apps, schema_editor):
    Stack = apps.get_model("stacks", "Stack")
    for obj in Stack.objects.all():
        previous_modified_at = obj.modified_at
        if obj.subtitle and not obj.notes:
            obj.notes = obj.subtitle
            obj.subtitle = obj.subtitle.split("\n")[0]
            if "." in obj.subtitle:
                obj.subtitle = obj.subtitle.split(".")[0] + "."
            obj.save()
            Stack.objects.filter(pk=obj.pk).update(modified_at=previous_modified_at)


class Migration(migrations.Migration):
    dependencies = [
        ("stacks", "0004_rename_description_historicalstack_subtitle_and_more"),
    ]

    operations = [
        migrations.RunPython(split_description_to_subtitle_and_notes),
    ]
