# Generated by Django 4.0.8 on 2022-12-01 18:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stacks", "0005_auto_20221109_0124"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalstack",
            name="subtitle",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stack",
            name="subtitle",
            field=models.TextField(blank=True, null=True),
        ),
    ]
