# Generated by Django 4.0.8 on 2022-11-28 21:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stacks", "0005_auto_20221109_0124"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalstack",
            name="hashid",
            field=models.CharField(
                blank=True, db_index=True, max_length=254, null=True
            ),
        ),
        migrations.AddField(
            model_name="stack",
            name="hashid",
            field=models.CharField(
                blank=True, db_index=True, max_length=254, null=True
            ),
        ),
    ]
