# Generated by Django 4.0.8 on 2022-12-01 21:19

from django.db import migrations


def clear_stale_stack_reports(apps, schema_editor):
    Stack = apps.get_model("stacks", "Stack")

    for s in Stack.objects.all():
        previous_modified_at = s.modified_at
        to_remove = []
        for r in s.reports.all():
            if r.deleted:
                to_remove.append(r)
        for r in to_remove:
            s.reports.remove(r)
        if len(to_remove) > 0:
            s.save()
        Stack.objects.filter(pk=s.pk).update(modified_at=previous_modified_at)


class Migration(migrations.Migration):
    dependencies = [
        ("stacks", "0006_alter_historicalstack_subtitle_alter_stack_subtitle"),
    ]

    operations = [
        migrations.RunPython(clear_stale_stack_reports),
    ]
