# Generated by Django 4.0.8 on 2022-11-28 21:59

from django.db import migrations
from utils.encryption import create_unique_ox_id


def add_hashes(apps, schema_editor):
    Stack = apps.get_model("stacks", "Stack")

    for obj in Stack.objects.all():
        previous_modified_at = obj.modified_at
        obj.hashid = create_unique_ox_id(obj.pk, Stack, "hashid")
        obj.save()
        Stack.objects.filter(pk=obj.pk).update(modified_at=previous_modified_at)


class Migration(migrations.Migration):
    dependencies = [
        ("stacks", "0006_historicalstack_hashid_stack_hashid"),
    ]

    operations = [
        migrations.RunPython(add_hashes),
    ]
