# Generated by Django 4.0.8 on 2022-11-28 22:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stacks", "0007_auto_20221128_2159"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalstack",
            name="legacy_pk",
        ),
        migrations.RemoveField(
            model_name="stack",
            name="legacy_pk",
        ),
    ]
