# Generated by Django 4.0.8 on 2022-12-05 19:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stacks", "0007_auto_20221201_2119"),
        ("stacks", "0009_rename_hashid_historicalstack_ox_id_and_more"),
    ]

    operations = []
