# Generated by Django 3.2.13 on 2022-05-20 20:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collaboration", "0002_auto_20220520_1555"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalinboxitem",
            name="comment",
        ),
        migrations.RemoveField(
            model_name="inboxitem",
            name="comment",
        ),
        migrations.AddField(
            model_name="comment",
            name="edited",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalcomment",
            name="edited",
            field=models.BooleanField(default=False),
        ),
    ]
