# Generated by Django 3.2.13 on 2022-05-23 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("collaboration", "0003_auto_20220520_2019"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalinboxitem",
            name="comment",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="collaboration.comment",
            ),
        ),
        migrations.AddField(
            model_name="inboxitem",
            name="comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="collaboration.comment",
            ),
        ),
    ]
