# Generated by Django 3.2.13 on 2022-05-24 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collaboration", "0004_auto_20220523_1723"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalinboxitem",
            name="hashid",
            field=models.CharField(
                blank=True, db_index=True, max_length=254, null=True
            ),
        ),
        migrations.AddField(
            model_name="inboxitem",
            name="hashid",
            field=models.CharField(
                blank=True, db_index=True, max_length=254, null=True
            ),
        ),
    ]
