# Generated by Django 4.0.8 on 2022-11-08 01:02
from django.apps.registry import Apps, apps as global_apps
from django.db import migrations


def remove_stale_subscriptions(apps: Apps, schema_editor):
    GenericPermission = apps.get_model("organizations", "GenericPermission")
    TeamMember = apps.get_model("organizations", "TeamMember")
    OrganizationRole = apps.get_model("organizations", "OrganizationRole")
    ObjectSubscription = apps.get_model("collaboration", "ObjectSubscription")
    InboxItem = apps.get_model("collaboration", "InboxItem")

    for obj_sub in ObjectSubscription.objects.all():
        can_know = False
        if (
            GenericPermission.objects.filter(
                user=obj_sub.user,
                object_id=obj_sub.object_id,
                content_type=obj_sub.content_type,
            )
            .exclude(
                can_score=False,
                can_read=False,
                can_write=False,
                can_administer=False,
            )
            .all()
            .count()
            > 0
        ):
            can_know = True
        if not can_know:
            for tm in TeamMember.objects.filter(user=obj_sub.user):
                if (
                    GenericPermission.objects.filter(
                        team=tm.team,
                        object_id=obj_sub.object_id,
                        content_type=obj_sub.content_type,
                    )
                    .exclude(
                        can_score=False,
                        can_read=False,
                        can_write=False,
                        can_administer=False,
                    )
                    .all()
                    .count()
                    > 0
                ):
                    can_know = True

        if not can_know:
            for org_role in OrganizationRole.objects.filter(user=obj_sub.user):
                if (
                    GenericPermission.objects.filter(
                        organization=org_role.organization,
                        object_id=obj_sub.object_id,
                        content_type=obj_sub.content_type,
                    )
                    .exclude(
                        can_score=False,
                        can_read=False,
                        can_write=False,
                        can_administer=False,
                    )
                    .all()
                    .count()
                    > 0
                ):
                    can_know = True
                    break

            if not can_know:
                # print("Deleting OS %s" % obj_sub)
                obj_sub.delete()

    for ii in InboxItem.objects.all():
        can_know = False
        if (
            GenericPermission.objects.filter(
                user=ii.user,
                object_id=obj_sub.object_id,
                content_type=obj_sub.content_type,
            )
            .exclude(
                can_score=False,
                can_read=False,
                can_write=False,
                can_administer=False,
            )
            .all()
            .count()
            > 0
        ):
            can_know = True
        if not can_know:
            for tm in TeamMember.objects.filter(user=ii.user):
                if (
                    GenericPermission.objects.filter(
                        team=tm.team,
                        object_id=obj_sub.object_id,
                        content_type=obj_sub.content_type,
                    )
                    .exclude(
                        can_score=False,
                        can_read=False,
                        can_write=False,
                        can_administer=False,
                    )
                    .all()
                    .count()
                    > 0
                ):
                    can_know = True

        if not can_know:
            for org_role in OrganizationRole.objects.filter(user=ii.user):
                if (
                    GenericPermission.objects.filter(
                        organization=org_role.organization,
                        object_id=obj_sub.object_id,
                        content_type=obj_sub.content_type,
                    )
                    .exclude(
                        can_score=False,
                        can_read=False,
                        can_write=False,
                        can_administer=False,
                    )
                    .all()
                    .count()
                    > 0
                ):
                    can_know = True
                    break

            if not can_know:
                # print("Deleting II %s" % ii)
                ii.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("collaboration", "0006_alter_historicalcomment_options_and_more"),
    ]

    operations = [
        migrations.RunPython(remove_stale_subscriptions),
    ]
