# Generated by Django 4.0.8 on 2022-11-28 22:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collaboration", "0007_auto_20221108_0102"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="hashid",
            field=models.CharField(
                blank=True, db_index=True, max_length=254, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalcomment",
            name="hashid",
            field=models.CharField(
                blank=True, db_index=True, max_length=254, null=True
            ),
        ),
    ]
