# Generated by Django 4.0.8 on 2022-11-28 22:25

from django.db import migrations
from utils.encryption import create_unique_ox_id


def add_hashes(apps, schema_editor):
    Comment = apps.get_model("collaboration", "Comment")

    for obj in Comment.objects.all():
        previous_modified_at = obj.modified_at
        obj.hashid = create_unique_ox_id(obj.pk, Comment, "hashid")
        obj.save()
        Comment.objects.filter(pk=obj.pk).update(modified_at=previous_modified_at)


class Migration(migrations.Migration):
    dependencies = [
        ("collaboration", "0008_comment_hashid_historicalcomment_hashid"),
    ]

    operations = [
        migrations.RunPython(add_hashes),
    ]
