# Generated by Django 4.0.8 on 2022-11-28 22:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("collaboration", "0009_auto_20221128_2225"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="legacy_pk",
        ),
        migrations.RemoveField(
            model_name="historicalcomment",
            name="legacy_pk",
        ),
        migrations.RemoveField(
            model_name="historicalinboxitem",
            name="legacy_pk",
        ),
        migrations.RemoveField(
            model_name="historicalobjectsubscription",
            name="legacy_pk",
        ),
        migrations.RemoveField(
            model_name="inboxitem",
            name="legacy_pk",
        ),
        migrations.RemoveField(
            model_name="objectsubscription",
            name="legacy_pk",
        ),
    ]
