# Generated by Django 4.0.8 on 2022-11-30 00:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("collaboration", "0010_remove_comment_legacy_pk_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="hashid",
            new_name="ox_id",
        ),
        migrations.RenameField(
            model_name="historicalcomment",
            old_name="hashid",
            new_name="ox_id",
        ),
        migrations.RenameField(
            model_name="historicalinboxitem",
            old_name="hashid",
            new_name="ox_id",
        ),
        migrations.RenameField(
            model_name="inboxitem",
            old_name="hashid",
            new_name="ox_id",
        ),
    ]
