# Generated by Django 3.2.12 on 2022-04-13 19:03

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):
    dependencies = [
        ("frameworks", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="criteria",
            managers=[
                ("authorized_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="framework",
            managers=[
                ("authorized_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name="criteria",
            name="name",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="framework",
            name="name",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="historicalcriteria",
            name="name",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="historicalframework",
            name="name",
            field=models.TextField(null=True),
        ),
    ]
