# Generated by Django 3.2.13 on 2022-04-25 19:17

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):
    dependencies = [
        ("frameworks", "0004_alter_criteria_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="criteria",
            managers=[
                ("objects_with_deleted", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name="criteria",
            name="legacy_pk",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="framework",
            name="legacy_pk",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="historicalcriteria",
            name="legacy_pk",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="historicalframework",
            name="legacy_pk",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
