# Generated by Django 4.0.6 on 2022-07-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frameworks", "0007_alter_historicalcriteria_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="criteria",
            name="index",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="historicalcriteria",
            name="index",
            field=models.IntegerField(default=0),
        ),
    ]
