# Generated by Django 4.0.6 on 2022-07-28 11:01

from django.db import migrations


def add_indexes(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Framework = apps.get_model("frameworks", "Framework")
    Criteria = apps.get_model("frameworks", "Criteria")
    for f in Framework.objects.all():
        index = 0
        for c in f.criteria_set.order_by("created_at").all():
            previous_modified_at = c.modified_at
            c.index = index
            c.save()
            index += 1
            Criteria.objects.filter(pk=c.pk).update(modified_at=previous_modified_at)


class Migration(migrations.Migration):
    dependencies = [
        ("frameworks", "0008_criteria_index_historicalcriteria_index"),
    ]

    operations = [
        migrations.RunPython(add_indexes),
    ]
