# Generated by Django 4.0.6 on 2022-08-03 19:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frameworks", "0010_auto_20220729_0851"),
    ]

    operations = [
        migrations.AlterField(
            model_name="criteria",
            name="index",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalcriteria",
            name="index",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
