# Generated by Django 4.0.7 on 2022-09-08 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("frameworks", "0011_alter_criteria_index_alter_historicalcriteria_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="framework",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="frameworks.framework",
            ),
        ),
        migrations.AddField(
            model_name="historicalframework",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="frameworks.framework",
            ),
        ),
    ]
