# Generated by Django 4.0.8 on 2022-11-09 01:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frameworks", "0012_framework_parent_historicalframework_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="framework",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalframework",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
