# Generated by Django 4.0.8 on 2022-11-09 01:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("frameworks", "0013_framework_notes_historicalframework_notes"),
    ]

    operations = [
        migrations.RenameField(
            model_name="framework",
            old_name="description",
            new_name="subtitle",
        ),
        migrations.RenameField(
            model_name="historicalframework",
            old_name="description",
            new_name="subtitle",
        ),
    ]
