# Generated by Django 4.0.8 on 2022-11-09 01:14
from django.db import migrations


def split_description_to_subtitle_and_notes(apps, schema_editor):
    Framework = apps.get_model("frameworks", "Framework")
    for obj in Framework.objects.all():
        if obj.subtitle and not obj.notes:
            previous_modified_at = obj.modified_at
            obj.notes = obj.subtitle
            obj.subtitle = obj.subtitle.split("\n")[0]
            if "." in obj.subtitle:
                obj.subtitle = obj.subtitle.split(".")[0] + "."
            obj.save()
            Framework.objects.filter(pk=obj.pk).update(modified_at=previous_modified_at)


class Migration(migrations.Migration):
    dependencies = [
        ("frameworks", "0014_rename_description_framework_subtitle_and_more"),
    ]

    operations = [
        migrations.RunPython(split_description_to_subtitle_and_notes),
    ]
