# Generated by Django 4.0.8 on 2022-12-01 18:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frameworks", "0015_auto_20221109_0114"),
    ]

    operations = [
        migrations.AlterField(
            model_name="framework",
            name="subtitle",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalframework",
            name="subtitle",
            field=models.TextField(blank=True, null=True),
        ),
    ]
