# Generated by Django 4.0.8 on 2022-11-28 22:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frameworks", "0015_auto_20221109_0114"),
    ]

    operations = [
        migrations.AddField(
            model_name="criteria",
            name="hashid",
            field=models.CharField(
                blank=True, db_index=True, max_length=254, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalcriteria",
            name="hashid",
            field=models.CharField(
                blank=True, db_index=True, max_length=254, null=True
            ),
        ),
    ]
