# Generated by Django 4.0.8 on 2022-11-28 22:19

from django.db import migrations
from utils.encryption import create_unique_ox_id


def add_hashes(apps, schema_editor):
    Criteria = apps.get_model("frameworks", "Criteria")

    for obj in Criteria.objects.all():
        previous_modified_at = obj.modified_at
        obj.hashid = create_unique_ox_id(obj.pk, Criteria, "hashid")
        obj.save()
        Criteria.objects.filter(pk=obj.pk).update(modified_at=previous_modified_at)


class Migration(migrations.Migration):
    dependencies = [
        ("frameworks", "0016_criteria_hashid_historicalcriteria_hashid"),
    ]

    operations = [
        migrations.RunPython(add_hashes),
    ]
