# Generated by Django 4.0.8 on 2022-11-28 22:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frameworks", "0017_auto_20221128_2219"),
    ]

    operations = [
        migrations.AddField(
            model_name="framework",
            name="hashid",
            field=models.CharField(
                blank=True, db_index=True, max_length=254, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalframework",
            name="hashid",
            field=models.CharField(
                blank=True, db_index=True, max_length=254, null=True
            ),
        ),
    ]
