# Generated by Django 4.0.8 on 2022-11-28 22:24

from django.db import migrations
from utils.encryption import create_unique_ox_id


def add_hashes(apps, schema_editor):
    Framework = apps.get_model("frameworks", "Framework")

    for obj in Framework.objects.all():
        previous_modified_at = obj.modified_at
        obj.hashid = create_unique_ox_id(obj.pk, Framework, "hashid")
        obj.save()
        Framework.objects.filter(pk=obj.pk).update(modified_at=previous_modified_at)


class Migration(migrations.Migration):
    dependencies = [
        ("frameworks", "0018_framework_hashid_historicalframework_hashid"),
    ]

    operations = [
        migrations.RunPython(add_hashes),
    ]
