# Generated by Django 4.0.8 on 2022-11-28 22:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("frameworks", "0019_auto_20221128_2224"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="criteria",
            name="legacy_pk",
        ),
        migrations.RemoveField(
            model_name="framework",
            name="legacy_pk",
        ),
        migrations.RemoveField(
            model_name="historicalcriteria",
            name="legacy_pk",
        ),
        migrations.RemoveField(
            model_name="historicalframework",
            name="legacy_pk",
        ),
    ]
