# Generated by Django 4.0.8 on 2022-11-30 00:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "frameworks",
            "0020_remove_criteria_legacy_pk_remove_framework_legacy_pk_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="criteria",
            old_name="hashid",
            new_name="ox_id",
        ),
        migrations.RenameField(
            model_name="framework",
            old_name="hashid",
            new_name="ox_id",
        ),
        migrations.RenameField(
            model_name="historicalcriteria",
            old_name="hashid",
            new_name="ox_id",
        ),
        migrations.RenameField(
            model_name="historicalframework",
            old_name="hashid",
            new_name="ox_id",
        ),
    ]
