# Generated by Django 4.0.8 on 2022-12-05 19:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("frameworks", "0016_alter_framework_subtitle_and_more"),
        ("frameworks", "0021_rename_hashid_criteria_ox_id_and_more"),
    ]

    operations = []
