# Generated by Django 4.0.8 on 2023-02-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frameworks", "0022_merge_20221205_1941"),
    ]

    operations = [
        migrations.AddField(
            model_name="framework",
            name="has_skipped",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="framework",
            name="ox_score",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalframework",
            name="has_skipped",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalframework",
            name="ox_score",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=5, null=True
            ),
        ),
    ]
