# Generated by Django 4.0.8 on 2023-02-17 17:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("frameworks", "0024_auto_20230213_1329"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="framework",
            name="has_skipped",
        ),
        migrations.RemoveField(
            model_name="framework",
            name="ox_score",
        ),
        migrations.RemoveField(
            model_name="historicalframework",
            name="has_skipped",
        ),
        migrations.RemoveField(
            model_name="historicalframework",
            name="ox_score",
        ),
    ]
