# Generated by Django 4.1.9 on 2023-06-26 06:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frameworks", "0025_remove_framework_has_skipped_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="framework",
            name="gpt_context",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="framework",
            name="gpt_prompt",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalframework",
            name="gpt_context",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalframework",
            name="gpt_prompt",
            field=models.TextField(blank=True, null=True),
        ),
    ]
