# Generated by Django 3.2.12 on 2022-04-13 19:03

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="report",
            managers=[
                ("authorized_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="reportfeedback",
            managers=[
                ("authorized_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="scorecard",
            managers=[
                ("authorized_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="scorecardscore",
            managers=[
                ("authorized_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
