# Generated by Django 3.2.13 on 2022-04-25 19:17

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0003_auto_20220420_1817"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="reportfeedback",
            managers=[
                ("objects_with_deleted", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="scorecard",
            managers=[
                ("objects_with_deleted", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="scorecardscore",
            managers=[
                ("objects_with_deleted", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name="historicalreport",
            name="legacy_pk",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="historicalreportfeedback",
            name="legacy_pk",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="historicalscorecard",
            name="legacy_pk",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="historicalscorecardscore",
            name="legacy_pk",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="report",
            name="legacy_pk",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="reportfeedback",
            name="legacy_pk",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="scorecard",
            name="legacy_pk",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="scorecardscore",
            name="legacy_pk",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
