# Generated by Django 3.2.13 on 2022-04-25 23:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0004_auto_20220425_1917"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="report",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="reportfeedback",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="scorecard",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="scorecardscore",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="historicalreport",
            name="description",
        ),
        migrations.RemoveField(
            model_name="report",
            name="description",
        ),
    ]
