# Generated by Django 4.0.7 on 2022-09-08 16:29

from django.db import migrations


def combine_analytic_question_and_summary(apps, schema_editor):
    Report = apps.get_model("reports", "Report")
    for r in Report.objects.all():
        previous_modified_at = r.modified_at
        if r.analytic_question:
            if r.summary:
                r.summary = f"{r.summary}\n\nAnalytic Question: {r.analytic_question}"
            else:
                r.summary = r.analytic_question
            r.save()
            Report.objects.filter(pk=r.pk).update(modified_at=previous_modified_at)


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0006_alter_historicalreport_options_and_more"),
    ]

    operations = [
        migrations.RunPython(combine_analytic_question_and_summary),
    ]
