# Generated by Django 4.0.7 on 2022-09-08 16:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0007_auto_20220908_1629"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalreport",
            name="analytic_question",
        ),
        migrations.RemoveField(
            model_name="report",
            name="analytic_question",
        ),
    ]
