# Generated by Django 4.0.7 on 2022-10-03 23:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0008_remove_historicalreport_analytic_question_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalscorecard",
            name="framework_criteria_hash",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="scorecard",
            name="framework_criteria_hash",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
