# Generated by Django 4.0.8 on 2022-11-09 01:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0009_alter_historicalscorecard_framework_criteria_hash_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalreport",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="report",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
