# Generated by Django 4.0.8 on 2022-11-09 01:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0010_historicalreport_notes_report_notes"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicalreport",
            old_name="summary",
            new_name="subtitle",
        ),
        migrations.RenameField(
            model_name="report",
            old_name="summary",
            new_name="subtitle",
        ),
    ]
