# Generated by Django 4.0.8 on 2022-12-01 18:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frameworks", "0016_alter_framework_subtitle_and_more"),
        ("sources", "0009_auto_20221109_0122"),
        ("reports", "0012_auto_20221109_0118"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalreport",
            name="subtitle",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="report",
            name="frameworks",
            field=models.ManyToManyField(
                blank=True, null=True, to="frameworks.framework"
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="sources",
            field=models.ManyToManyField(blank=True, null=True, to="sources.source"),
        ),
        migrations.AlterField(
            model_name="report",
            name="subtitle",
            field=models.TextField(blank=True, null=True),
        ),
    ]
