# Generated by Django 4.0.8 on 2022-11-28 21:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0012_auto_20221109_0118"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalreport",
            name="hashid",
            field=models.CharField(
                blank=True, db_index=True, max_length=254, null=True
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="hashid",
            field=models.CharField(
                blank=True, db_index=True, max_length=254, null=True
            ),
        ),
    ]
