# Generated by Django 4.0.8 on 2022-11-28 21:58

from django.db import migrations
from utils.encryption import create_unique_ox_id


def add_hashes(apps, schema_editor):
    Report = apps.get_model("reports", "Report")

    for obj in Report.objects.all():
        previous_modified_at = obj.modified_at
        obj.hashid = create_unique_ox_id(obj.pk, Report, "hashid")
        obj.save()
        Report.objects.filter(pk=obj.pk).update(modified_at=previous_modified_at)


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0013_historicalreport_hashid_report_hashid"),
    ]

    operations = [
        migrations.RunPython(add_hashes),
    ]
