# Generated by Django 4.0.8 on 2022-11-28 22:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0014_auto_20221128_2158"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalscorecard",
            name="hashid",
            field=models.CharField(
                blank=True, db_index=True, max_length=254, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalscorecardscore",
            name="hashid",
            field=models.CharField(
                blank=True, db_index=True, max_length=254, null=True
            ),
        ),
        migrations.AddField(
            model_name="scorecard",
            name="hashid",
            field=models.CharField(
                blank=True, db_index=True, max_length=254, null=True
            ),
        ),
        migrations.AddField(
            model_name="scorecardscore",
            name="hashid",
            field=models.CharField(
                blank=True, db_index=True, max_length=254, null=True
            ),
        ),
    ]
