# Generated by Django 4.0.8 on 2022-11-28 22:11

from django.db import migrations
from utils.encryption import create_unique_ox_id


def add_hashes(apps, schema_editor):
    Report = apps.get_model("reports", "Report")
    Scorecard = apps.get_model("reports", "Scorecard")
    ScorecardScore = apps.get_model("reports", "ScorecardScore")

    for obj in Report.objects.all():
        previous_modified_at = obj.modified_at
        obj.hashid = create_unique_ox_id(obj.pk, Report, "hashid")
        obj.save()
        Report.objects.filter(pk=obj.pk).update(modified_at=previous_modified_at)

    for obj in Scorecard.objects.all():
        obj.hashid = create_unique_ox_id(obj.pk, Scorecard, "hashid")
        obj.save()

    for obj in ScorecardScore.objects.all():
        obj.hashid = create_unique_ox_id(obj.pk, ScorecardScore, "hashid")
        obj.save()


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0015_historicalscorecard_hashid_and_more"),
    ]

    operations = [
        migrations.RunPython(add_hashes),
    ]
