# Generated by Django 4.0.8 on 2022-11-28 22:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0016_auto_20221128_2211"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalreport",
            name="legacy_pk",
        ),
        migrations.RemoveField(
            model_name="historicalreportfeedback",
            name="legacy_pk",
        ),
        migrations.RemoveField(
            model_name="historicalscorecard",
            name="legacy_pk",
        ),
        migrations.RemoveField(
            model_name="historicalscorecardscore",
            name="legacy_pk",
        ),
        migrations.RemoveField(
            model_name="report",
            name="legacy_pk",
        ),
        migrations.RemoveField(
            model_name="reportfeedback",
            name="legacy_pk",
        ),
        migrations.RemoveField(
            model_name="scorecard",
            name="legacy_pk",
        ),
        migrations.RemoveField(
            model_name="scorecardscore",
            name="legacy_pk",
        ),
    ]
