# Generated by Django 4.0.8 on 2022-11-29 22:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0017_remove_historicalreport_legacy_pk_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalreport",
            name="has_skipped",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalreport",
            name="ox_score",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="has_skipped",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="report",
            name="ox_score",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=5, null=True
            ),
        ),
    ]
