# Generated by Django 4.0.8 on 2022-11-29 22:32
from decimal import Decimal
from django.db import migrations
from utils.encryption import create_unique_ox_id


def add_hashes(apps, schema_editor):
    Report = apps.get_model("reports", "Report")
    Scorecard = apps.get_model("reports", "Scorecard")
    ScorecardScore = apps.get_model("reports", "ScorecardScore")

    for r in Report.objects.exclude(deleted=True).all().distinct():
        previous_modified_at = r.modified_at
        total_scores = Decimal(0)
        num_scores = Decimal(0)
        total_possible = Decimal(0)
        criteria_totals = {}
        criteria_weights = {}
        criteria_num_scores = {}

        for s in Scorecard.objects.filter(report=r).exclude(deleted=True).distinct():
            for sc in (
                ScorecardScore.objects.filter(scorecard=s)
                .exclude(deleted=True)
                .distinct()
            ):
                if sc.score or sc.score == 0:
                    if f"{sc.criteria.pk}" not in criteria_totals:
                        criteria_totals[f"{sc.criteria.pk}"] = 0
                    if f"{sc.criteria.pk}" not in criteria_num_scores:
                        criteria_num_scores[f"{sc.criteria.pk}"] = 0
                    criteria_totals[f"{sc.criteria.pk}"] += sc.score
                    criteria_weights[f"{sc.criteria.pk}"] = sc.criteria.weight
                    criteria_num_scores[f"{sc.criteria.pk}"] += 1
                    num_scores += 1
                else:
                    criteria_weights[f"{sc.criteria.pk}"] = sc.criteria.weight

        has_skipped = False
        for k, v in criteria_weights.items():
            if k in criteria_totals:
                total_scores += (
                    criteria_totals[k] / criteria_num_scores[k]
                ) * criteria_weights[k]
                total_possible += 10 * criteria_weights[k]
            else:
                total_scores += 0
                total_possible += 10 * criteria_weights[k]

            if k not in criteria_num_scores:
                has_skipped = True
            # r.has_skipped = False
        r.has_skipped = has_skipped

        if total_possible > 0:
            r.ox_score = Decimal(round(Decimal(100) * total_scores / total_possible))
        else:
            r.ox_score = None
        r.save()
        Report.objects.filter(pk=r.pk).update(modified_at=previous_modified_at)


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0018_historicalreport_has_skipped_and_more"),
    ]

    operations = [
        migrations.RunPython(add_hashes),
    ]
