# Generated by Django 4.0.8 on 2022-11-29 23:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0019_auto_20221129_2232"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalscorecard",
            name="has_skipped",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalscorecard",
            name="ox_score",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="scorecard",
            name="has_skipped",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="scorecard",
            name="ox_score",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=5, null=True
            ),
        ),
    ]
