# Generated by Django 4.0.8 on 2022-11-29 23:38

from django.db import migrations
from decimal import Decimal
from django.db import migrations
from utils.encryption import create_unique_ox_id


def add_hashes(apps, schema_editor):
    Report = apps.get_model("reports", "Report")
    Scorecard = apps.get_model("reports", "Scorecard")
    ScorecardScore = apps.get_model("reports", "ScorecardScore")

    for sc in Scorecard.objects.exclude(deleted=True).all():
        total_scores = 0
        max_scores = 0
        has_skipped = False
        for s in (
            ScorecardScore.objects.exclude(deleted=True)
            .filter(scorecard=sc)
            .all()
            .distinct()
        ):
            if s.score is not None:
                total_scores += s.score * s.criteria.weight
            max_scores += 10 * s.criteria.weight
            if s.score is None and s.score != 0:
                has_skipped = True

        sc.ox_score = None
        if max_scores > 0:
            sc.ox_score = Decimal(round(Decimal(100) * total_scores / max_scores))
        sc.has_skipped = has_skipped
        sc.save()


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0020_historicalscorecard_has_skipped_and_more"),
    ]

    operations = [
        migrations.RunPython(add_hashes),
    ]
