# Generated by Django 4.0.8 on 2022-11-29 23:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0021_auto_20221129_2338"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalreport",
            name="feedback_comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalreport",
            name="feedback_score",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="feedback_comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="report",
            name="feedback_score",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=5, null=True
            ),
        ),
    ]
