# Generated by Django 4.0.8 on 2022-11-29 23:55

from django.db import migrations
from decimal import Decimal
from django.db import migrations
from utils.encryption import create_unique_ox_id


def add_hashes(apps, schema_editor):
    Report = apps.get_model("reports", "Report")
    ReportFeedback = apps.get_model("reports", "ReportFeedback")

    for r in Report.objects.exclude(deleted=True).all():
        previous_modified_at = r.modified_at
        rf = ReportFeedback.objects.filter(report=r).exclude(comment="", score=None)
        if rf.count() > 1:
            raise Exception("Can't migrate, more than one feedback object")
        if rf.count() == 1:
            rf = rf[0]
            r.feedback_comment = rf.comment
            r.feedback_score = rf.score
            r.save()
            Report.objects.filter(pk=r.pk).update(modified_at=previous_modified_at)


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0022_historicalreport_feedback_comment_and_more"),
    ]

    operations = [
        migrations.RunPython(add_hashes),
    ]
