# Generated by Django 4.0.8 on 2022-11-30 00:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0023_auto_20221129_2355"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reportfeedback",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="reportfeedback",
            name="modified_by",
        ),
        migrations.RemoveField(
            model_name="reportfeedback",
            name="report",
        ),
        migrations.DeleteModel(
            name="HistoricalReportFeedback",
        ),
        migrations.DeleteModel(
            name="ReportFeedback",
        ),
    ]
