# Generated by Django 4.0.8 on 2022-11-30 00:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0024_remove_reportfeedback_created_by_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicalreport",
            old_name="hashid",
            new_name="ox_id",
        ),
        migrations.RenameField(
            model_name="historicalscorecard",
            old_name="hashid",
            new_name="ox_id",
        ),
        migrations.RenameField(
            model_name="historicalscorecardscore",
            old_name="hashid",
            new_name="ox_id",
        ),
        migrations.RenameField(
            model_name="report",
            old_name="hashid",
            new_name="ox_id",
        ),
        migrations.RenameField(
            model_name="scorecard",
            old_name="hashid",
            new_name="ox_id",
        ),
        migrations.RenameField(
            model_name="scorecardscore",
            old_name="hashid",
            new_name="ox_id",
        ),
    ]
