# Generated by Django 4.0.8 on 2022-12-05 19:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0014_alter_report_frameworks_alter_report_sources"),
        ("reports", "0025_rename_hashid_historicalreport_ox_id_and_more"),
    ]

    operations = []
