# Generated by Django 4.0.8 on 2022-12-20 13:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0026_merge_20221205_1941"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="report",
            name="frameworks",
        ),
    ]
