# Generated by Django 4.1.9 on 2023-06-26 06:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0027_remove_report_frameworks"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalreport",
            name="gpt_context",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalreport",
            name="gpt_prompt",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalscorecard",
            name="gpt_context",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalscorecard",
            name="gpt_prompt",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="report",
            name="gpt_context",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="report",
            name="gpt_prompt",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scorecard",
            name="gpt_context",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scorecard",
            name="gpt_prompt",
            field=models.TextField(blank=True, null=True),
        ),
    ]
