# Generated by Django 4.1.9 on 2023-06-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0028_historicalreport_gpt_context_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalscorecardscore",
            name="gpt_score",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=4, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalscorecardscore",
            name="gpt_scored_last",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="scorecardscore",
            name="gpt_score",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=4, null=True
            ),
        ),
        migrations.AddField(
            model_name="scorecardscore",
            name="gpt_scored_last",
            field=models.BooleanField(default=False),
        ),
    ]
