cacheFolder: ./.yarn/cache

compressionLevel: mixed

enableGlobalCache: false

nodeLinker: pnp

npmScopes:
  fortawesome:
    npmAlwaysAuth: true
    npmAuthToken: "${FONTAWESOME_NPM_TOKEN}"
    npmRegistryServer: "https://npm.fontawesome.com/"

yarnPath: .yarn/releases/yarn-4.12.0.cjs
