# Generated by Django 4.0.5 on 2022-06-23 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("history", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalobjecthistorychange",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical object history change",
                "verbose_name_plural": "historical object history changes",
            },
        ),
        migrations.AlterField(
            model_name="historicalobjecthistorychange",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="objecthistorychange",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="objecthistorychange",
            name="modified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_modified_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
