# Generated by Django 4.0.8 on 2022-11-28 22:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("history", "0002_alter_historicalobjecthistorychange_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalobjecthistorychange",
            name="legacy_pk",
        ),
        migrations.RemoveField(
            model_name="objecthistorychange",
            name="legacy_pk",
        ),
    ]
