# Generated by Django 3.2.12 on 2022-04-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0003_user_is_superuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalorganization",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalorganization",
            name="name",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="name",
            field=models.TextField(blank=True, null=True),
        ),
    ]
