# Generated by Django 3.2.12 on 2022-04-19 15:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0004_auto_20220413_1903"),
        ("organizations", "0004_auto_20220419_1439"),
    ]

    operations = []
