# Generated by Django 3.2.12 on 2022-04-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0005_merge_0004_auto_20220413_1903_0004_auto_20220419_1439"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalorganization",
            name="name",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="name",
            field=models.TextField(blank=True, null=True),
        ),
    ]
