# Generated by Django 3.2.13 on 2022-04-25 19:17

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0006_auto_20220419_1510"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="organization",
            managers=[
                ("objects_with_deleted", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="organizationrole",
            managers=[
                ("objects_with_deleted", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="team",
            managers=[
                ("objects_with_deleted", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="teammember",
            managers=[
                ("objects_with_deleted", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name="historicalorganization",
            name="legacy_pk",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="historicalorganizationrole",
            name="legacy_pk",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="historicalteam",
            name="legacy_pk",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="historicalteammember",
            name="legacy_pk",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="legacy_pk",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="organizationrole",
            name="legacy_pk",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="team",
            name="legacy_pk",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="legacy_pk",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
