# Generated by Django 3.2.13 on 2022-04-25 23:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0007_auto_20220425_1917"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="organization",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="organizationrole",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="team",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="teammember",
            managers=[],
        ),
    ]
