# Generated by Django 3.2.13 on 2022-05-25 21:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0010_auto_20220519_2000"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="hashid",
            field=models.CharField(
                blank=True, db_index=True, max_length=254, null=True
            ),
        ),
    ]
