# Generated by Django 3.2.13 on 2022-05-25 22:00

from django.db import migrations
from utils.encryption import create_unique_ox_id


def add_hashes(apps, schema_editor):
    MigrationUser = apps.get_model("organizations", "User")
    from organizations.models import User

    for u in MigrationUser.objects.all():
        previous_modified_at = u.modified_at
        u.hashid = create_unique_ox_id(u.pk, User, "hashid")
        u.save()
        MigrationUser.objects.filter(pk=u.pk).update(modified_at=previous_modified_at)


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0011_user_hashid"),
    ]

    operations = [
        migrations.RunPython(add_hashes),
    ]
