# Generated by Django 4.0.6 on 2022-08-01 11:33

from django.db import migrations
from django.apps.registry import Apps, apps as global_apps
from django.contrib.contenttypes.management import create_contenttypes


def cleanup_generic_permissions(apps, schema_editor):
    frameworks_config = global_apps.get_app_config("frameworks")
    create_contenttypes(frameworks_config)
    reports_config = global_apps.get_app_config("reports")
    create_contenttypes(reports_config)
    sources_config = global_apps.get_app_config("sources")
    create_contenttypes(sources_config)

    GenericPermission = apps.get_model("organizations", "GenericPermission")
    ContentType = apps.get_model("contenttypes", "ContentType")

    report_ct = ContentType.objects.get(app_label="reports", model="report")
    framework_ct = ContentType.objects.get(app_label="frameworks", model="framework")
    source_ct = ContentType.objects.get(app_label="sources", model="source")

    for gp in GenericPermission.objects.exclude(
        content_type__in=[report_ct, framework_ct, source_ct]
    ):
        gp.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0013_alter_historicalgenericpermission_options_and_more"),
    ]

    operations = [
        migrations.RunPython(cleanup_generic_permissions),
    ]
