# Generated by Django 4.0.6 on 2022-08-04 11:47

from django.db import migrations
from django.apps.registry import Apps, apps as global_apps
from django.contrib.contenttypes.management import create_contenttypes


def cleanup_orphaned_tags(apps: Apps, schema_editor):
    frameworks_config = global_apps.get_app_config("frameworks")
    create_contenttypes(frameworks_config)
    reports_config = global_apps.get_app_config("reports")
    create_contenttypes(reports_config)
    sources_config = global_apps.get_app_config("sources")
    create_contenttypes(sources_config)

    Tag = apps.get_model("organizations", "Tag")
    TaggedObject = apps.get_model("organizations", "TaggedObject")
    ContentType = apps.get_model("contenttypes", "ContentType")
    framework_ct = ContentType.objects.get(app_label="frameworks", model="framework")
    report_ct = ContentType.objects.get(app_label="reports", model="report")
    source_ct = ContentType.objects.get(app_label="sources", model="source")

    # Framework = apps.get_model("frameworks", "Framework")
    # Source = apps.get_model("sources", "Source")
    # # Report = apps.get_model("reports", "Report")
    from frameworks.models import Framework
    from reports.models import Report
    from sources.models import Source

    for to in TaggedObject.objects.all():
        obj = None
        if to.content_type == framework_ct:
            try:
                obj = Framework.objects.get(pk=to.object_id)
            except Framework.DoesNotExist:
                pass

        if to.content_type == report_ct:
            try:
                obj = Report.objects.get(pk=to.object_id)
            except Report.DoesNotExist:
                pass

        if to.content_type == source_ct:
            try:
                obj = Source.objects.get(pk=to.object_id)
            except Source.DoesNotExist:
                pass

        if obj is None:
            to.delete()
    for tag in Tag.objects.all():
        if tag.taggedobject_set.exclude(deleted=True).count() == 0:
            tag.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0014_auto_20220801_1133"),
    ]

    operations = [
        migrations.RunPython(cleanup_orphaned_tags),
    ]
