# Generated by Django 4.0.7 on 2022-09-27 21:44
from django.db import migrations
from django.apps.registry import Apps, apps as global_apps
from django.contrib.contenttypes.management import create_contenttypes


def clear_stale_gps(apps: Apps, schema_editor):
    frameworks_config = global_apps.get_app_config("frameworks")
    create_contenttypes(frameworks_config)
    reports_config = global_apps.get_app_config("reports")
    create_contenttypes(reports_config)
    sources_config = global_apps.get_app_config("sources")
    create_contenttypes(sources_config)

    Tag = apps.get_model("organizations", "Tag")
    TaggedObject = apps.get_model("organizations", "TaggedObject")
    ContentType = apps.get_model("contenttypes", "ContentType")
    framework_ct = ContentType.objects.get(app_label="frameworks", model="framework")
    report_ct = ContentType.objects.get(app_label="reports", model="report")
    source_ct = ContentType.objects.get(app_label="sources", model="source")

    # Framework = apps.get_model("frameworks", "Framework")
    # Source = apps.get_model("sources", "Source")
    # Report = apps.get_model("reports", "Report")
    GenericPermission = apps.get_model("organizations", "GenericPermission")
    Framework = apps.get_model("frameworks", "Framework")
    Source = apps.get_model("sources", "Source")
    Report = apps.get_model("reports", "Report")

    for f in Framework.objects.all():
        if f.deleted:
            print(f"Cleanup: {f}")
            gp = GenericPermission.objects.filter(
                content_type=framework_ct, object_id=f.pk
            ).delete()

    for s in Source.objects.all():
        if s.deleted:
            print(f"Cleanup: {s}")
            gp = GenericPermission.objects.filter(
                content_type=source_ct, object_id=s.pk
            ).delete()

    for r in Report.objects.all():
        if r.deleted:
            print(f"Cleanup: {r}")
            gp = GenericPermission.objects.filter(
                content_type=report_ct, object_id=r.pk
            ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0016_auto_20220923_1859"),
        ("reports", "0008_remove_historicalreport_analytic_question_and_more"),
        ("frameworks", "0012_framework_parent_historicalframework_parent"),
        ("sources", "0006_alter_historicalsource_options_and_more"),
    ]

    operations = [
        migrations.RunPython(clear_stale_gps),
    ]
