# Generated by Django 4.0.7 on 2022-09-27 22:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0017_auto_20220927_2144"),
    ]

    operations = [
        migrations.AddField(
            model_name="genericpermission",
            name="can_score_only",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalgenericpermission",
            name="can_score_only",
            field=models.BooleanField(default=False),
        ),
    ]
