# Generated by Django 4.0.7 on 2022-09-28 21:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0018_genericpermission_can_score_only_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="genericpermission",
            old_name="can_score_only",
            new_name="can_score",
        ),
        migrations.RenameField(
            model_name="historicalgenericpermission",
            old_name="can_score_only",
            new_name="can_score",
        ),
    ]
