# Generated by Django 4.0.7 on 2022-09-29 04:05
from django.db import migrations
from django.apps.registry import Apps, apps as global_apps


def update_gps_with_cascading_permissions(apps: Apps, schema_editor):
    GenericPermission = apps.get_model("organizations", "GenericPermission")
    GenericPermission.objects.filter(can_write=True).update(
        can_read=True, can_score=True
    )
    GenericPermission.objects.filter(can_administer=True).update(
        can_write=True, can_read=True, can_score=True
    )


class Migration(migrations.Migration):
    dependencies = [
        (
            "organizations",
            "0019_rename_can_score_only_genericpermission_can_score_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(update_gps_with_cascading_permissions),
    ]
