# Generated by Django 4.0.7 on 2022-10-19 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0009_alter_historicalscorecard_framework_criteria_hash_and_more"),
        ("stacks", "0002_rename_summary_historicalstack_description_and_more"),
        ("frameworks", "0012_framework_parent_historicalframework_parent"),
        ("organizations", "0020_auto_20220929_0405"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="pinned_framework",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="frameworks.framework",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="pinned_report",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="reports.report",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="pinned_stack",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="stacks.stack",
            ),
        ),
    ]
