# Generated by Django 4.0.7 on 2022-10-24 21:59
from django.apps.registry import Apps, apps as global_apps
from django.db import migrations


def delete_inaccurate_team_memberships(apps: Apps, schema_editor):
    Team = apps.get_model("organizations", "Team")
    TeamMember = apps.get_model("organizations", "TeamMember")
    User = apps.get_model("organizations", "User")
    Organization = apps.get_model("organizations", "Organization")
    OrganizationRole = apps.get_model("organizations", "OrganizationRole")

    for org_role in OrganizationRole.objects.all():
        if not org_role.can_view and not org_role.can_manage:
            print(f"Cleaned up org non-member: {org_role.user}.")
            org_role.delete()

    for tm in TeamMember.objects.all():
        if (
            OrganizationRole.objects.filter(
                user=tm.user, organization=tm.team.organization
            ).count()
            == 0
        ):
            print(
                f"Cleaned up detached team membership: {tm.user} in {tm.team} ({tm.team.organization})."
            )
            tm.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0021_user_pinned_framework_user_pinned_report_and_more"),
    ]

    operations = [
        migrations.RunPython(delete_inaccurate_team_memberships),
    ]
