# Generated by Django 4.0.8 on 2022-11-08 23:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0023_user_created_at_user_modified_at"),
    ]

    operations = []
