# Generated by Django 4.0.8 on 2022-11-28 22:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0024_auto_20221108_2354"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalorganization",
            name="hashid",
            field=models.CharField(
                blank=True, db_index=True, max_length=254, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalteam",
            name="hashid",
            field=models.CharField(
                blank=True, db_index=True, max_length=254, null=True
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="hashid",
            field=models.CharField(
                blank=True, db_index=True, max_length=254, null=True
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="hashid",
            field=models.CharField(
                blank=True, db_index=True, max_length=254, null=True
            ),
        ),
    ]
