# Generated by Django 4.0.8 on 2022-11-28 22:13

from django.db import migrations
from utils.encryption import create_unique_ox_id


def add_hashes(apps, schema_editor):
    Organization = apps.get_model("organizations", "Organization")
    Team = apps.get_model("organizations", "Team")

    for obj in Organization.objects.all():
        previous_modified_at = obj.modified_at
        obj.hashid = create_unique_ox_id(obj.pk, Organization, "hashid")
        obj.save()
        Organization.objects.filter(pk=obj.pk).update(modified_at=previous_modified_at)

    for obj in Team.objects.all():
        previous_modified_at = obj.modified_at
        obj.hashid = create_unique_ox_id(obj.pk, Team, "hashid")
        obj.save()
        Team.objects.filter(pk=obj.pk).update(modified_at=previous_modified_at)


class Migration(migrations.Migration):
    dependencies = [
        (
            "organizations",
            "0025_historicalorganization_hashid_historicalteam_hashid_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(add_hashes),
    ]
