# Generated by Django 4.0.8 on 2022-11-28 22:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0026_auto_20221128_2213"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaltag",
            name="hashid",
            field=models.CharField(
                blank=True, db_index=True, max_length=254, null=True
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="hashid",
            field=models.CharField(
                blank=True, db_index=True, max_length=254, null=True
            ),
        ),
    ]
