# Generated by Django 4.0.8 on 2022-11-28 22:19

from django.db import migrations
from utils.encryption import create_unique_ox_id


def add_hashes(apps, schema_editor):
    Tag = apps.get_model("organizations", "Tag")

    for obj in Tag.objects.all():
        previous_modified_at = obj.modified_at
        obj.hashid = create_unique_ox_id(obj.pk, Tag, "hashid")
        obj.save()
        Tag.objects.filter(pk=obj.pk).update(modified_at=previous_modified_at)


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0027_historicaltag_hashid_tag_hashid"),
    ]

    operations = [
        migrations.RunPython(add_hashes),
    ]
