# Generated by Django 4.0.8 on 2022-11-28 22:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0028_auto_20221128_2219"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="genericpermission",
            name="legacy_pk_uid",
        ),
        migrations.RemoveField(
            model_name="historicalgenericpermission",
            name="legacy_pk_uid",
        ),
        migrations.RemoveField(
            model_name="historicalorganization",
            name="legacy_pk",
        ),
        migrations.RemoveField(
            model_name="historicalorganizationrole",
            name="legacy_pk",
        ),
        migrations.RemoveField(
            model_name="historicaltag",
            name="legacy_pk",
        ),
        migrations.RemoveField(
            model_name="historicaltaggedobject",
            name="legacy_pk",
        ),
        migrations.RemoveField(
            model_name="historicalteam",
            name="legacy_pk",
        ),
        migrations.RemoveField(
            model_name="historicalteammember",
            name="legacy_pk",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="legacy_pk",
        ),
        migrations.RemoveField(
            model_name="organizationrole",
            name="legacy_pk",
        ),
        migrations.RemoveField(
            model_name="tag",
            name="legacy_pk",
        ),
        migrations.RemoveField(
            model_name="taggedobject",
            name="legacy_pk",
        ),
        migrations.RemoveField(
            model_name="team",
            name="legacy_pk",
        ),
        migrations.RemoveField(
            model_name="teammember",
            name="legacy_pk",
        ),
        migrations.RemoveField(
            model_name="user",
            name="legacy_password",
        ),
        migrations.RemoveField(
            model_name="user",
            name="legacy_password_migrated",
        ),
        migrations.RemoveField(
            model_name="user",
            name="legacy_pk",
        ),
        migrations.RemoveField(
            model_name="user",
            name="legacy_user",
        ),
    ]
