# Generated by Django 4.0.8 on 2022-11-30 00:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0029_remove_genericpermission_legacy_pk_uid_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicalorganization",
            old_name="hashid",
            new_name="ox_id",
        ),
        migrations.RenameField(
            model_name="historicaltag",
            old_name="hashid",
            new_name="ox_id",
        ),
        migrations.RenameField(
            model_name="historicalteam",
            old_name="hashid",
            new_name="ox_id",
        ),
        migrations.RenameField(
            model_name="organization",
            old_name="hashid",
            new_name="ox_id",
        ),
        migrations.RenameField(
            model_name="tag",
            old_name="hashid",
            new_name="ox_id",
        ),
        migrations.RenameField(
            model_name="team",
            old_name="hashid",
            new_name="ox_id",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="hashid",
            new_name="ox_id",
        ),
    ]
