# Generated by Django 4.1.10 on 2023-07-13 18:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0030_rename_hashid_historicalorganization_ox_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="public_signup",
            field=models.BooleanField(default=False),
        ),
    ]
