# Generated by Django 3.2.12 on 2022-04-13 19:03

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):
    dependencies = [
        ("sources", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="source",
            managers=[
                ("authorized_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="sourcefeedback",
            managers=[
                ("authorized_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name="historicalsource",
            name="name",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="source",
            name="name",
            field=models.TextField(null=True),
        ),
    ]
