# Generated by Django 3.2.12 on 2022-04-20 18:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sources", "0002_auto_20220413_1903"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="sourcefeedback",
            managers=[],
        ),
    ]
