# Generated by Django 3.2.13 on 2022-04-25 19:17

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):
    dependencies = [
        ("sources", "0003_alter_sourcefeedback_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="sourcefeedback",
            managers=[
                ("objects_with_deleted", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name="historicalsource",
            name="legacy_pk",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="historicalsourcefeedback",
            name="legacy_pk",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="source",
            name="legacy_pk",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="sourcefeedback",
            name="legacy_pk",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
