# Generated by Django 3.2.13 on 2022-04-25 23:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sources", "0004_auto_20220425_1917"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="source",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="sourcefeedback",
            managers=[],
        ),
    ]
