# Generated by Django 4.0.8 on 2022-11-09 01:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sources", "0006_alter_historicalsource_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsource",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="source",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
