# Generated by Django 4.0.8 on 2022-11-09 01:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sources", "0007_historicalsource_notes_source_notes"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicalsource",
            old_name="description",
            new_name="subtitle",
        ),
        migrations.RenameField(
            model_name="source",
            old_name="description",
            new_name="subtitle",
        ),
    ]
