# Generated by Django 4.0.8 on 2022-11-09 01:22

from django.db import migrations


def split_description_to_subtitle_and_notes(apps, schema_editor):
    Source = apps.get_model("sources", "Source")
    for obj in Source.objects.all():
        if obj.subtitle and not obj.notes:
            previous_modified_at = obj.modified_at
            obj.notes = obj.subtitle
            obj.subtitle = obj.subtitle.split("\n")[0]
            if "." in obj.subtitle:
                obj.subtitle = obj.subtitle.split(".")[0] + "."
            obj.save()
            Source.objects.filter(pk=obj.pk).update(modified_at=previous_modified_at)


class Migration(migrations.Migration):
    dependencies = [
        ("sources", "0008_rename_description_historicalsource_subtitle_and_more"),
    ]

    operations = [
        migrations.RunPython(split_description_to_subtitle_and_notes),
    ]
