# Generated by Django 4.0.8 on 2022-11-28 21:55

from django.db import migrations
from utils.encryption import create_unique_ox_id


def add_hashes(apps, schema_editor):
    Source = apps.get_model("sources", "Source")

    for obj in Source.objects.all():
        previous_modified_at = obj.modified_at
        obj.hashid = create_unique_ox_id(obj.pk, Source, "hashid")
        obj.save()
        Source.objects.filter(pk=obj.pk).update(modified_at=previous_modified_at)


class Migration(migrations.Migration):
    dependencies = [
        ("sources", "0010_historicalsource_hashid_source_hashid"),
    ]

    operations = [
        migrations.RunPython(add_hashes),
    ]
