# Generated by Django 4.0.8 on 2022-11-28 22:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sources", "0011_auto_20221128_2155"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalsource",
            name="legacy_pk",
        ),
        migrations.RemoveField(
            model_name="historicalsourcefeedback",
            name="legacy_pk",
        ),
        migrations.RemoveField(
            model_name="source",
            name="legacy_pk",
        ),
        migrations.RemoveField(
            model_name="sourcefeedback",
            name="legacy_pk",
        ),
    ]
