# Generated by Django 4.0.8 on 2022-11-30 00:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sources", "0012_remove_historicalsource_legacy_pk_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicalsource",
            old_name="hashid",
            new_name="ox_id",
        ),
        migrations.RenameField(
            model_name="source",
            old_name="hashid",
            new_name="ox_id",
        ),
    ]
