# Generated by Django 4.0.8 on 2022-12-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedfile",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="userfiles"),
        ),
    ]
